### ISSUE TITLE
Point to Line distance error

### ISSUE THREAD

**Issue by pauljurczak** [jan-mue/geometer#46]
I'm using Python 3.8.10 with geometer 0.2.3. This code snippet:
```
p0 = Point(1, 2, 0)
l0 = Line(Point(0, 0, 0), Point(3, 0, 0))
print(dist(p0, l0))
```
produces this exception:
```
Traceback (most recent call last):
  File "/home/paul/upwork/pick/code/test-geometer.py", line 14, in <module>
    print(dist(p0, l0))
  File "/home/paul/upwork/pick/code/.pick/lib/python3.8/site-packages/geometer/operators.py", line 243, in dist
    return dist(q.project(p), p)
  File "/home/paul/upwork/pick/code/.pick/lib/python3.8/site-packages/geometer/point.py", line 511, in project
    l = self.perpendicular(pt)
  File "/home/paul/upwork/pick/code/.pick/lib/python3.8/site-packages/geometer/point.py", line 495, in perpendicular
    return self.mirror(through).join(through)
  File "/home/paul/upwork/pick/code/.pick/lib/python3.8/site-packages/geometer/point.py", line 596, in mirror
    result = m1.meet(m2)
  File "/home/paul/upwork/pick/code/.pick/lib/python3.8/site-packages/geometer/point.py", line 339, in meet
    return meet(self, *others)
  File "/home/paul/upwork/pick/code/.pick/lib/python3.8/site-packages/geometer/point.py", line 113, in meet
    return _join_meet_duality(*args, intersect_lines=True)
  File "/home/paul/upwork/pick/code/.pick/lib/python3.8/site-packages/geometer/point.py", line 65, in _join_meet_duality
    raise LinearDependenceError("Arguments are not linearly independent.")
geometer.exceptions.LinearDependenceError: Arguments are not linearly independent.
```

**Comment by jan-mue** [comment]
This should be fixed in version 0.3.
